[config]
default_to_workspace = false

[env]
LOCAL_GOLEM_CLI = "../golem/target/debug/golem-cli"
# Use `makers -e OFFICIAL=1` to use official Golem CLI
GOLEM_CLI = { source = "${OFFICIAL}", default_value = "${LOCAL_GOLEM_CLI}", mapping = { "1" = "golem-cli" } }

# -- Extra --

[tasks.build-golem-cli]
condition = { condition_type = "Or", env_not_set = ["OFFICIAL"], env = { "OFFICIAL" = "0" } }
command = "cargo"
args = ["build", "--manifest-path", "../golem/golem-cli/Cargo.toml"]

[tasks.golem-cli]
description = "Use local golem-cli. Ex: makers golem-cli --version"
command = "${GOLEM_CLI}"
args = ["${@}"]
dependencies = ["build-golem-cli"]

# -- Generated & Modified --

[tasks."add-stub-dependency-src/components/counter-src/components/counter"]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "src/components/counter-stub/wit", "--dest-wit-root", "src/components/counter/wit", "--overwrite", "--update-cargo-toml"]
command = "${GOLEM_CLI}"
cwd = "."
dependencies = ["generate-src/components/counter-stub"]

[tasks."add-stub-dependency-src/components/counter-src/components/runtime_loop"]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "src/components/counter-stub/wit", "--dest-wit-root", "src/components/runtime_loop/wit", "--overwrite", "--update-cargo-toml"]
command = "${GOLEM_CLI}"
cwd = "."
dependencies = ["generate-src/components/counter-stub"]

[tasks."add-stub-dependency-src/components/runtime_loop-src/components/counter"]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "src/components/runtime_loop-stub/wit", "--dest-wit-root", "src/components/counter/wit", "--overwrite", "--update-cargo-toml"]
command = "${GOLEM_CLI}"
cwd = "."
dependencies = ["generate-src/components/runtime_loop-stub"]

[tasks."add-stub-dependency-src/components/runtime_loop-src/components/runtime_loop"]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "src/components/runtime_loop-stub/wit", "--dest-wit-root", "src/components/runtime_loop/wit", "--overwrite", "--update-cargo-toml"]
command = "${GOLEM_CLI}"
cwd = "."
dependencies = ["generate-src/components/runtime_loop-stub"]

[tasks.build]
args = ["build"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.build-flow]
dependencies = ["build-golem-cli", "build", "post-build"]

[tasks.build-release]
args = ["build", "--release"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.clean]
args = ["clean"]
command = "cargo-component"

[tasks."compose-release-src/components/counter"]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasip1/release/counter.wasm", "--stub-wasm", "target/wasm32-wasip1/release/counter_stub.wasm", "--stub-wasm", "target/wasm32-wasip1/release/runtime_loop_stub.wasm", "--dest-wasm", "target/wasm32-wasip1/release/counter_composed.wasm"]
command = "${GOLEM_CLI}"
cwd = "."

[tasks."compose-release-src/components/runtime_loop"]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasip1/release/runtime_loop.wasm", "--stub-wasm", "target/wasm32-wasip1/release/counter_stub.wasm", "--stub-wasm", "target/wasm32-wasip1/release/runtime_loop_stub.wasm", "--dest-wasm", "target/wasm32-wasip1/release/runtime_loop_composed.wasm"]
command = "${GOLEM_CLI}"
cwd = "."

[tasks."compose-src/components/counter"]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasip1/debug/counter.wasm", "--stub-wasm", "target/wasm32-wasip1/debug/counter_stub.wasm", "--stub-wasm", "target/wasm32-wasip1/debug/runtime_loop_stub.wasm", "--dest-wasm", "target/wasm32-wasip1/debug/counter_composed.wasm"]
command = "${GOLEM_CLI}"
cwd = "."

[tasks."compose-src/components/runtime_loop"]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasip1/debug/runtime_loop.wasm", "--stub-wasm", "target/wasm32-wasip1/debug/counter_stub.wasm", "--stub-wasm", "target/wasm32-wasip1/debug/runtime_loop_stub.wasm", "--dest-wasm", "target/wasm32-wasip1/debug/runtime_loop_composed.wasm"]
command = "${GOLEM_CLI}"
cwd = "."

[tasks.default]
alias = "build"

[tasks."generate-src/components/counter-stub"]
args = ["stubgen", "generate", "-s", "src/components/counter/wit", "-d", "src/components/counter-stub"]
command = "${GOLEM_CLI}"
cwd = "."

[tasks."generate-src/components/runtime_loop-stub"]
args = ["stubgen", "generate", "-s", "src/components/runtime_loop/wit", "-d", "src/components/runtime_loop-stub"]
command = "${GOLEM_CLI}"
cwd = "."

[tasks.post-build]
dependencies = ["compose-src/components/counter", "compose-src/components/runtime_loop"]

[tasks.post-build-release]
dependencies = ["compose-release-src/components/counter", "compose-release-src/components/runtime_loop"]

[tasks.regenerate-stubs]
dependencies = ["add-stub-dependency-src/components/counter-src/components/counter", "add-stub-dependency-src/components/counter-src/components/runtime_loop", "add-stub-dependency-src/components/runtime_loop-src/components/counter", "add-stub-dependency-src/components/runtime_loop-src/components/runtime_loop"]

[tasks.release-build-flow]
dependencies = ["build-golem-cli", "build-release", "post-build-release"]

[tasks.test]
args = ["test"]
command = "cargo-component"
dependencies = ["clean"]
