[config]
default_to_workspace = false

[tasks.add-stub-dependency-golem_async-golem_async]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "golem_async-stub/wit", "--dest-wit-root", "golem_async/wit", "--overwrite", "--update-cargo-toml"]
command = "golem-cli"
cwd = "."
dependencies = ["generate-golem_async-stub"]

[tasks.add-stub-dependency-golem_async-runtime_loop]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "golem_async-stub/wit", "--dest-wit-root", "runtime_loop/wit", "--overwrite", "--update-cargo-toml"]
command = "golem-cli"
cwd = "."
dependencies = ["generate-golem_async-stub"]

[tasks.add-stub-dependency-runtime_loop-golem_async]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "runtime_loop-stub/wit", "--dest-wit-root", "golem_async/wit", "--overwrite", "--update-cargo-toml"]
command = "golem-cli"
cwd = "."
dependencies = ["generate-runtime_loop-stub"]

[tasks.add-stub-dependency-runtime_loop-runtime_loop]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "runtime_loop-stub/wit", "--dest-wit-root", "runtime_loop/wit", "--overwrite", "--update-cargo-toml"]
command = "golem-cli"
cwd = "."
dependencies = ["generate-runtime_loop-stub"]

[tasks.build]
args = ["build"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.build-flow]
dependencies = ["build", "post-build"]

[tasks.build-release]
args = ["build", "--release"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.clean]
args = ["clean"]
command = "cargo-component"

[tasks.compose-golem_async]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/debug/golem_async.wasm", "--stub-wasm", "target/wasm32-wasi/debug/golem_async_stub.wasm", "--stub-wasm", "target/wasm32-wasi/debug/runtime_loop_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/golem_async_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.compose-release-golem_async]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/release/golem_async.wasm", "--stub-wasm", "target/wasm32-wasi/release/golem_async_stub.wasm", "--stub-wasm", "target/wasm32-wasi/release/runtime_loop_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/golem_async_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.compose-release-runtime_loop]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/release/runtime_loop.wasm", "--stub-wasm", "target/wasm32-wasi/release/golem_async_stub.wasm", "--stub-wasm", "target/wasm32-wasi/release/runtime_loop_stub.wasm", "--dest-wasm", "target/wasm32-wasi/release/runtime_loop_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.compose-runtime_loop]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasi/debug/runtime_loop.wasm", "--stub-wasm", "target/wasm32-wasi/debug/golem_async_stub.wasm", "--stub-wasm", "target/wasm32-wasi/debug/runtime_loop_stub.wasm", "--dest-wasm", "target/wasm32-wasi/debug/runtime_loop_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.default]
alias = "build"

[tasks.generate-golem_async-stub]
args = ["stubgen", "generate", "-s", "golem_async/wit", "-d", "golem_async-stub"]
command = "golem-cli"
cwd = "."

[tasks.generate-runtime_loop-stub]
args = ["stubgen", "generate", "-s", "runtime_loop/wit", "-d", "runtime_loop-stub"]
command = "golem-cli"
cwd = "."

[tasks.post-build]
dependencies = ["compose-golem_async", "compose-runtime_loop"]

[tasks.post-build-release]
dependencies = ["compose-release-golem_async", "compose-release-runtime_loop"]

[tasks.regenerate-stubs]
dependencies = ["add-stub-dependency-golem_async-golem_async", "add-stub-dependency-golem_async-runtime_loop", "add-stub-dependency-runtime_loop-golem_async", "add-stub-dependency-runtime_loop-runtime_loop"]

[tasks.release-build-flow]
dependencies = ["build-release", "post-build-release"]

[tasks.test]
args = ["test"]
command = "cargo-component"
dependencies = ["clean"]
