apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: Golem Async with Initial File System
spec:
  components:
    - name: counter
      type: wasm
      properties:
        inputWasm: ../../../out/build/counter/component.wasm
        outputWasm: ../../../out/components/counter.wasm
        wit: wit
        files:
          - sourcePath: https://picsum.photos/200/300
            targetPath: /images/random_picture.jpg
          - sourcePath: ../../../default_counter.json
            targetPath: /default_counter.json
          - sourcePath: last_counter_value.txt
            targetPath: /last_value.txt
            permissions: read-write
          - sourcePath: ./images
            targetPath: /images
