package golem:component-golem-async;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface api-golem-async {
  add: func(value: u64);
  get: func() -> u64;
  run-all-tasks: func();
}

world golem-async {
  import golem:component-runtime-loop-stub/stub-runtime-loop;
  export api-golem-async;
}
