package golem:component;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface api {
  start-loop: func();
}

world runtime-loop {
  export api;
}
