apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: Golem Async with Initial File System
spec:
  components:
    - name: runtime_loop
      type: wasm
      properties:
        inputWasm: ../../../out/build/runtime_loop/component.wasm
        outputWasm: ../../../out/components/runtime_loop.wasm
        wit: wit
        files:
          - sourcePath: https://picsum.photos/200/300
            targetPath: /images/random_picture.jpg
            permissions: read-only
